### ISSUE TITLE
simple docker-compose

### ISSUE THREAD

**Issue by davidsarkany** [FrankPetrilli/boringtun-docker#1]
Hi!

Can you add simple docker-compose.yml config?

**Comment by davidsarkany** [comment]
docker-compose.yml
```
version: "3.7"
services:
  boringtun:
    privileged: true
    image: frankpetrilli/boringtun
    container_name: boringtun
    cap_add:
      - NET_ADMIN
    ports:
      - "587:587/udp"
    devices:
      - "/dev/net/tun:/dev/net/tun"
    volumes:
      - "./config/wg0.conf:/etc/wireguard/wg0.conf"
    logging:
      driver: "json-file"
      options:
        max-size: "400k"
        max-file: "20"
    environment:
      INTERFACE_NAME: "wg0"
      WG_SUDO: "1"
      WG_QUICK_USERSPACE_IMPLEMENTATION: "/app/boringtun"
    entrypoint: /bin/bash
    command: -c "wg-quick up wg0 && sleep infinity"
```

wg0.conf

```
[Interface]
Address = 10.192.0.1/24
PrivateKey = yyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy
ListenPort = 587
PreUp = echo "1" > /proc/sys/net/ipv4/ip_forward
PostUp = iptables-legacy -t nat -A POSTROUTING -o eth0 -s 10.192.0.0/24 -j MASQUERADE
[Peer]
PublicKey = zzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzzz
AllowedIPs = 10.192.0.2/32
```
